name: Pre deploy tasks for Birb Helper

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    needs: [eslint]
    if: "!contains(github.event.head_commit.message, '[skip docker]')"
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Birb Helper Docker Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/birb-helper:latest
  sentry:
    needs: [eslint]
    if: "!contains(github.event.head_commit.message, '[skip sentry release]')"
    name: Sentry release creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3
      - name: Create Sentry Release
        uses: getsentry/action-release@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
  eslint:
    name: ESLint syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g eslint
      - run: npx eslint -v
      - run: npx eslint . --ext .js
