name: Prettier formatting check

on: [push, pull_request, workflow_dispatch]

jobs:
  prettier:
    name: Run prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: action/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm install prettier
      - run: npx prettier --check "./src/**/*.js"
