name: Prettier formatting check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  pull_request_review:
  workflow_dispatch:

jobs:
  prettier:
    name: Run prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm install -g prettier
      - run: npx prettier -v
      - run: npx prettier --check "./src/**/*.js"
